# Generated by Django 5.1.1 on 2024-10-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="questionary",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
